config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root 'users#index'

  namespace :api do
    namespace :v1 do
      resources :users, only:  [:index, :show] do
        resources :posts, only:  [:index] do
          resources :comments, only:  [:index, :create]
        end
      end
    end
  end

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create, :destroy]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, allow_blank: false, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User'
  has_many :comments, foreign_key: 'post_id', dependent: :destroy
  has_many :likes, foreign_key: 'post_id', dependent: :destroy

  after_save :update_posts_counter
  before_destroy :update_posts_counter_on_destroy

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def update_posts_counter_on_destroy
    author.update_columns('posts_counter' => author.posts_counter - 1)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  before_action :authorize_request
  def index
    @posts = Post.where(author_id: params[:author_id])
    if @posts.empty?
      json_response({ msg: 'no post or user found' }, 400)
    else
      render json: @posts
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @user = current_user
    @posts = @user.posts.includes(:comments)

    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  def show
    @post = Post.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @post }
    end
  end

  def new
    @post = Post.new
    @user = current_user
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to user_post_url(current_user, @post), notice: 'Post was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @user = User.find(@post.author_id)
    @post.destroy
    redirect_to user_url(@user)
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text, :comments_counter, :likes_counter)
  end
end

app/views/posts/index.html.erb
<section class="container">  

    <div class="user-box">
        <img class="image-user" src=<%= @user.photo %> alt="user"/>
        <div class="user-info">
            <p class="user-name"><%= @user.name %></p>
            <p class="user-post">Number of posts: <%= @user.posts_counter%></p> 
        </div>   
    </div>   

    <% @posts.each do |post| %>
        <div class="post-info">
            <%= link_to user_post_path(@user.id, post.id) do %>
                <p class="post-title">Post : <%= post.title %> by <%= post.author.name %></p>
                <p class="post-text"><%= post.text %></p>
                <p class="post-text-2">Comments: <span><%= post.comments_counter || 0 %>, Likes: <%= post.likes_counter || 0 %></span></p>  
            <% end %>      
        </div>
        
        <div class="comment-info">
            <% post.recent_comments.each do |comment| %>
                <p> 
                    <span>
                        <%= comment.author.name %>:
                    </span> 
                    <span>
                        <%= comment.text %>
                    </span>
                </p>
            <% end %>
        </div>            
        
    <% end %>   

    <div class="button-user">
        <%= button_to 'Add New Post', new_user_post_url(id: @user.id), method: :get, class: "button"%>
        <button class="button">
            Pagination
        </button>
    </div>
    
</section>

app/views/posts/new.html.erb
<section class="container">
    <p class="post-title">Add New Post :</p>
    <%= form_with model: @post, url: user_posts_path, method: :post, local: true, class: "form-control" do |form| %>

        <%= form.hidden_field :comments_counter, value: 0 %>
        <%= form.hidden_field :likes_counter, value: 0 %>
        
        <div class="mb-3 mt-3">
            <%= form.label :title %>
            <%= form.text_field :title, placeholder: "Title", required: true, class: "form-post-title" %>        
        </div>

        <div>
            <%= form.label :text %>
            <%= form.text_area :text, placeholder: "Type your post here!", rows: 20, required: true,  class: "form-post-text" %>        
        </div>

        <div>
            <%= form.submit "Save", class: "button" %>
        </div>
    <% end %>
</section>

app/views/posts/show.html.erb
<section class="container">    
    <div class="post-info">
        <div class="post-title-box">
            <p class="post-title">Post : <%= @post.title %> by <%= @post.author.name %></p>
            <p class="comment-text">Comments: <%= @post.comments_counter || 0 %>, Likes: <%= @post.likes_counter || 0 %></p>
        </div>
        <p><%= @post.text %></p>
    </div>
    <div class="comment-info">
        <% @post.recent_comments.each do |comment| %>
            <div>
                <p class="post-title">Comments</p>
                <p> 
                    <span>
                        <%= comment.author.name %>:
                    </span> 
                    <span>
                        <%= comment.text %>
                    </span>
                </p>                
            </div>
            <% if can? :destroy, comment %>
                <%= button_to "Delete", user_post_comment_path(@post.author, @post, comment), method: :delete, class: 'button' %>
            <% end %>         
        <% end %>
    </div>
    <div class="button-user">
        <% if can? :destroy, @post %>
            <%= button_to "Delete Post", user_post_path(@post.author, @post), method: :delete, class: "button" %>
        <% end %>
        <%= button_to "Back", user_path(@post.author, @post), method: :get, class: "button" %>
        <%= button_to "Add Comment", new_user_post_comment_path(@post.author, @post), method: :get, class: "button" %>
        <div >
            <%= form_with model: @like,  url: "/users/#{params['user_id']}/posts/#{params['id']}/likes", method: :post , local: true do |form|%>
                <%= form.submit "Like", class: 'button' %>
            <% end %>
        </div>
    </div>
</section>